#1
stages:
  - test

    # # These are cache settings that we really don't use because each job is built on sperate vm
    # variables:
    #   SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
    #   COURSIER_CACHE: sbt-cache/coursier #only needed if you use coursier
    # 
    # cache:
    #   # key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
    #   key: "main" # contains either the branch or the tag, so it's caching per branch
    #   untracked: true
    #   paths:
    #     - "sbt-cache/ivy/cache"
    #     - "sbt-cache/boot"
    #     - "sbt-cache/sbtboot"
    #     - "sbt-cache/target"
    #     - "sbt-cache/coursier" #only needed if you use coursier

test:p2p-test-network-ubuntu-preloaded:
  stage: test 
  tags:
    - preloaded-ubuntu1804 

  script:
    - ./scripts/install_bnfc.sh
    - sudo sbt -Dsbt.log.noformat=true clean rholang/bnfc:generate node/docker
    - sudo python3.6 -m pip install argparse docker pexpect requests
    - sudo ./scripts/p2p-test-tool.py -b -p 1
