stages:
  - build
  - test
  - deploy


# build:rosette:
#   stage: build
#   image: nixos/nix
#   script:
#     - cd rosette
#     - nix-build
#     - ./run.sh rbl/rosette/tests/simple_add.rbl


build:p2p-test-network:
  stage: build
  image: docker:stable
  #image: ubuntu:xenial 

  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  variables:
    DOCKER_DRIVER: overlay2

  services:
  - docker:dind

  before_script:
      #- ./scripts/install_docker.sh 
  - docker info

  script:
    #- ./scripts/install_deps_ubuntu1604.sh 
    #- sudo apt-get -yq install python3-minimal python3-pexpect python3-pip
    #- apt-get -yq install sudo
    - apk add sudo
    - apk add bash 
    - apk add python3 
    - sudo pip3 install argparse docker pexpect
    - ./scripts/p2p-test-network.sh

  # build:test_artifact_creation:
  #   stage: build 
  #   image: ubuntu:xenial 
  #   script:
  #     - ./scripts/install_deps_ubuntu1604.sh 
  #     - sbt -Dsbt.log.noformat=true clean rholang/bnfc:generate node/debian:packageBin node/rpm:packageBin node/universal:packageZipTarball
  # 
  # build:core:
  #   stage: build
  #   image: ubuntu:xenial 
  #   script:
  #     - ./scripts/install_deps_ubuntu1604.sh 
  #     - ./scripts/build_core.sh
  # 
  # deploy:
  #   stage: deploy
  #   artifacts:
  #     paths:
  #     - public
  #   only:
  #   - master
  #   - dev
  #   script:
  #   - sbt -Dsbt.log.noformat=true clean rholang/bnfc:generate node/debian:packageBin node/rpm:packageBin node/universal:packageZipTarball 
