language: none
dist: trusty
sudo: required
services:
  - docker

    #docker exec rchain-dev sh -c "mkdir -p /src/rchain; cd /src/rchain; /src/rchain/scripts/ci-install-deps.sh"
    #- docker exec -it rchain-dev /bin/bash
    #- echo $TRAVIS_REPO_SLUG
    #- ls -lhat 



#   - docker ps -a
#   - docker exec -it rchain-dev sh -c "pwd"
#   - exit

    #- docker run -d -it --name rchain-dev ubuntu:16.04
    #- docker exec rchain-dev sh -c "mkdir -p /src/rchain"
    #- docker cp . rchain-dev:/src/rchain/
    # - docker pull ubuntu:16.04 
    #   - docker run -d \
    #         -it \
    #         --name rchain-dev \
    #         -v "$(pwd):/src/rchain" \
    #         ubuntu:16.04
    #before_install:

install:
  - docker run -d -it --name rchain-dev -v "$(pwd):/src/rchain" ubuntu:16.04
  - docker exec rchain-dev sh -c "cd /src/rchain; /src/rchain/scripts/ci-install-deps.sh"
  - docker exec rchain-dev sh -c "cd /src/rchain; /src/rchain/scripts/ci-build-subprojects.sh" 
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
notifications:
  email:
    recipients:
      - jeremy@pyrofex.net
    on_success: never
    on_failure: always
# addons:
#     apt:
#         sources:
#             - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
#         packages:
#             - sbt
#             - jflex
#             - haskell-platform

