language: scala
scala:
  - 2.12.4
sbt_args: -no-colors
dist: trusty
# env:
#   - SUBPROJECT=rosette
#   - SUBPROJECT=core
#
script:
  - ./scripts/build-subprojects.sh
sudo: required
install:
  - ./scripts/ci-install-deps.sh
  - ./scripts/ci-build-subprojects.sh
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
notifications:
  email:
    recipients:
      - jeremy@pyrofex.net
    on_success: never
    on_failure: always
addons:
    apt:
        sources:
            - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        packages:
            - sbt
            - jflex
            - haskell-platform


