sudo: required
dist: trusty

matrix:
  include:
  - language: scala
    python:
      - "3.6"
    env: SUBPROJECT=p2p-test-network
    scala: 2.12.4
    sbt_args: -no-colors
    addons:
      apt:
        sources:
          - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        packages:
          - rpm

before_script:
  - pyenv global system 3.6 # Workaround for travis-ci/issues/8363
  - sudo pip install argparse docker pexpect
script:
  - ./scripts/build-subprojects.sh

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"

after_success:
  - "./scripts/create-artifacts.sh"

deploy:
  provider: releases
  api_key: "$GITHUB_RELEASES_API_TOKEN_PUBLIC_REPO"
  file_glob: true
  file:
    - "node/target/*.deb"
    - "node/target/rpm/RPMS/noarch/*.rpm"
    - "node/target/universal/*.tgz"
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email:
    recipients: rchain-makers@pyrofex.net
    on_success: never
    on_failure: never 
