language: scala
scala:
  - 2.12.4
sbt_args: -no-colors
dist: trusty
sudo: required
services:
  - docker

    #docker exec rchain-dev sh -c "mkdir -p /src/rchain; cd /src/rchain; /src/rchain/scripts/ci-install-deps.sh"
    #- docker exec -it rchain-dev /bin/bash
    #- echo $TRAVIS_REPO_SLUG
    #- ls -lhat 
before_install:
  - docker pull ubuntu:16.04 
  - docker run -d -it --name rchain-dev ubuntu:16.04
  - docker ps -a
  - docker exec rchain-dev sh -c "mkdir -p /src/rchain"
  - docker cp ./* /src/rchain/
  - docker exec rchain-dev sh -c "cd /src/rchain; /src/rchain/scripts/ci-install-deps.sh"
install:
  - ./scripts/ci-install-deps.sh
  - ./scripts/ci-build-subprojects.sh
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
notifications:
  email:
    recipients:
      - jeremy@pyrofex.net
    on_success: never
    on_failure: always
addons:
    apt:
        sources:
            - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        packages:
            - sbt
            - jflex
            - haskell-platform

